// https://meteor.unca.edu/registrar/class-schedules/api/v1/courses/2023/spring/
const data = [
  {
    CRN: 10174,
    Code: "CSCI 182.001",
    Department: "CSCI",
    Title: "Intro to Programming: Media Applications",
    Instructors: [{ Username: "awhitley", Name: "Whitley, Adam" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T19:30:00Z",
    EndTime: "2019-05-07T20:45:00Z",
    Location: { FullLocation: "ZEI 201", Building: "ZEI", Room: "201" },
    EnrollmentCurrent: 19,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10498,
    Code: "CSCI 183.001",
    Department: "CSCI",
    Title: "Intro to Programming: Numerical Applications",
    Instructors: [{ Username: "msarris", Name: "Sarris, Michael" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T18:00:00Z",
    EndTime: "2019-05-07T19:15:00Z",
    Location: { FullLocation: "ZEI 201", Building: "ZEI", Room: "201" },
    EnrollmentCurrent: 21,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10488,
    Code: "CSCI 185.001",
    Department: "CSCI",
    Title: "Intro Programming: Web Development",
    Instructors: [{ Username: "svanwart", Name: "Van Wart, Sarah" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T13:30:00Z",
    EndTime: "2019-05-07T14:45:00Z",
    Location: { FullLocation: "ZEI 203", Building: "ZEI", Room: "203" },
    EnrollmentCurrent: 19,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11146,
    Code: "CSCI 185.002",
    Department: "CSCI",
    Title: "Intro Programming: Web Develop",
    Instructors: [{ Username: "svanwart", Name: "Van Wart, Sarah" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T15:00:00Z",
    EndTime: "2019-05-07T16:15:00Z",
    Location: { FullLocation: "ZEI 203", Building: "ZEI", Room: "203" },
    EnrollmentCurrent: 20,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11377,
    Code: "CSCI 185.D01",
    Department: "CSCI",
    Title: "Intro Programming: Web Develop",
    Instructors: [{ Username: "svanwart", Name: "Van Wart, Sarah" }],
    Hours: 3,
    Days: "TR",
    StartTime: "2019-05-07T17:20:00Z",
    EndTime: "2019-05-07T19:15:00Z",
    Location: { FullLocation: "AVER ", Building: null, Room: null },
    EnrollmentCurrent: 1,
    EnrollmentMax: 1,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: true,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "Off-Campus",
    Async: false,
  },
  {
    CRN: 10500,
    Code: "CSCI 201.001",
    Department: "CSCI",
    Title: "Intro to Object-Oriented Programming",
    Instructors: [{ Username: "kbogert", Name: "Bogert, Kenneth" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T15:00:00Z",
    EndTime: "2019-05-07T16:15:00Z",
    Location: { FullLocation: "WHI 008", Building: "WHI", Room: "008" },
    EnrollmentCurrent: 18,
    EnrollmentMax: 25,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10766,
    Code: "CSCI 201.002",
    Department: "CSCI",
    Title: "Intro to Object-Oriented Progr",
    Instructors: [{ Username: "kbogert", Name: "Bogert, Kenneth" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T16:30:00Z",
    EndTime: "2019-05-07T17:45:00Z",
    Location: { FullLocation: "ZEI 203", Building: "ZEI", Room: "203" },
    EnrollmentCurrent: 24,
    EnrollmentMax: 24,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10176,
    Code: "CSCI 202.001",
    Department: "CSCI",
    Title: "Intro to Data Structures",
    Instructors: [{ Username: "awhitley", Name: "Whitley, Adam" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T15:00:00Z",
    EndTime: "2019-05-07T16:15:00Z",
    Location: { FullLocation: "ZEI 201", Building: "ZEI", Room: "201" },
    EnrollmentCurrent: 20,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10177,
    Code: "CSCI 202.002",
    Department: "CSCI",
    Title: "Intro to Data Structures",
    Instructors: [{ Username: "awhitley", Name: "Whitley, Adam" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T16:30:00Z",
    EndTime: "2019-05-07T17:45:00Z",
    Location: { FullLocation: "ZEI 201", Building: "ZEI", Room: "201" },
    EnrollmentCurrent: 18,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10501,
    Code: "CSCI 235.001",
    Department: "CSCI",
    Title: "Systems I",
    Instructors: [{ Username: "msarris", Name: "Sarris, Michael" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T13:30:00Z",
    EndTime: "2019-05-07T14:45:00Z",
    Location: { FullLocation: "ZEI 201", Building: "ZEI", Room: "201" },
    EnrollmentCurrent: 21,
    EnrollmentMax: 24,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10499,
    Code: "CSCI 280.001",
    Department: "CSCI",
    Title: "Computer Science Seminar",
    Instructors: [{ Username: "ksanft", Name: "Sanft, Kevin" }],
    Hours: 1,
    Days: "M",
    StartTime: "2019-05-07T12:00:00Z",
    EndTime: "2019-05-07T13:15:00Z",
    Location: { FullLocation: "RRO 217", Building: "RRO", Room: "217" },
    EnrollmentCurrent: 15,
    EnrollmentMax: 25,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10566,
    Code: "CSCI 313.001",
    Department: "CSCI",
    Title: "Virtual Reality",
    Instructors: [{ Username: "kbogert", Name: "Bogert, Kenneth" }],
    Hours: 4,
    Days: "TR",
    StartTime: "2019-05-07T13:55:00Z",
    EndTime: "2019-05-07T15:35:00Z",
    Location: { FullLocation: "RRO 223", Building: "RRO", Room: "223" },
    EnrollmentCurrent: 9,
    EnrollmentMax: 9,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10502,
    Code: "CSCI 338.001",
    Department: "CSCI",
    Title: "Software Engineering",
    Instructors: [{ Username: "bmixon", Name: "Mixon, Brian" }],
    Hours: 3,
    Days: "TR",
    StartTime: "2019-05-07T12:00:00Z",
    EndTime: "2019-05-07T13:40:00Z",
    Location: { FullLocation: "ZEI 203", Building: "ZEI", Room: "203" },
    EnrollmentCurrent: 13,
    EnrollmentMax: 24,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10405,
    Code: "CSCI 344.001",
    Department: "CSCI",
    Title: "Advanced Web Technology",
    Instructors: [{ Username: "svanwart", Name: "Van Wart, Sarah" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T18:00:00Z",
    EndTime: "2019-05-07T19:15:00Z",
    Location: { FullLocation: "ZEI 203", Building: "ZEI", Room: "203" },
    EnrollmentCurrent: 22,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11147,
    Code: "CSCI 347.001",
    Department: "CSCI",
    Title: "Game Programming",
    Instructors: [{ Username: "mcameron", Name: "Cameron, Marietta" }],
    Hours: 3,
    Days: "TR",
    StartTime: "2019-05-07T12:00:00Z",
    EndTime: "2019-05-07T13:40:00Z",
    Location: { FullLocation: "RRO 223", Building: "RRO", Room: "223" },
    EnrollmentCurrent: 16,
    EnrollmentMax: 18,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [
      {
        Days: "TR",
        StartTime: "2019-05-07T12:00:00Z",
        EndTime: "2019-05-07T13:40:00Z",
        Location: { FullLocation: "RRO 217", Building: "RRO", Room: "217" },
        Async: false,
      },
    ],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11145,
    Code: "CSCI 364.001",
    Department: "CSCI",
    Title: "Cybersecurity",
    Instructors: [{ Username: "msarris", Name: "Sarris, Michael" }],
    Hours: 3,
    Days: "TR",
    StartTime: "2019-05-07T19:15:00Z",
    EndTime: "2019-05-07T20:55:00Z",
    Location: { FullLocation: "RRO 223", Building: "RRO", Room: "223" },
    EnrollmentCurrent: 18,
    EnrollmentMax: 18,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11148,
    Code: "CSCI 373.001",
    Department: "CSCI",
    Title: "ST: Dynamic Data Visualization",
    Instructors: [{ Username: "mcmcclur", Name: "McClure, Mark" }],
    Hours: 3,
    Days: "TR",
    StartTime: "2019-05-07T13:55:00Z",
    EndTime: "2019-05-07T15:35:00Z",
    Location: { FullLocation: "ZEI 203", Building: "ZEI", Room: "203" },
    EnrollmentCurrent: 14,
    EnrollmentMax: 12,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: false,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11150,
    Code: "CSCI 373.002",
    Department: "CSCI",
    Title: "ST:Natural Language Processing",
    Instructors: [{ Username: "frashid", Name: "Rashid, Farzana" }],
    Hours: 3,
    Days: "TR",
    StartTime: "2019-05-07T17:20:00Z",
    EndTime: "2019-05-07T19:00:00Z",
    Location: { FullLocation: "ZEI 201", Building: "ZEI", Room: "201" },
    EnrollmentCurrent: 7,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10496,
    Code: "CSCI 431.001",
    Department: "CSCI",
    Title: "Org of Programming Languages",
    Instructors: [{ Username: "frashid", Name: "Rashid, Farzana" }],
    Hours: 3,
    Days: "TR",
    StartTime: "2019-05-07T13:55:00Z",
    EndTime: "2019-05-07T15:35:00Z",
    Location: { FullLocation: "ZEI 201", Building: "ZEI", Room: "201" },
    EnrollmentCurrent: 8,
    EnrollmentMax: 24,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11151,
    Code: "CSCI 441.001",
    Department: "CSCI",
    Title: "Numerical Analysis",
    Instructors: [{ Username: "skaplan", Name: "Kaplan, Samuel" }],
    Hours: 3,
    Days: "MWF",
    StartTime: "2019-05-07T16:30:00Z",
    EndTime: "2019-05-07T17:20:00Z",
    Location: { FullLocation: "RRO 212", Building: "RRO", Room: "212" },
    EnrollmentCurrent: 7,
    EnrollmentMax: 12,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10539,
    Code: "CSCI 480.001",
    Department: "CSCI",
    Title: "Capstone I",
    Instructors: [{ Username: "ksanft", Name: "Sanft, Kevin" }],
    Hours: 2,
    Days: "WF",
    StartTime: "2019-05-07T12:00:00Z",
    EndTime: "2019-05-07T13:15:00Z",
    Location: { FullLocation: "RRO 217", Building: "RRO", Room: "217" },
    EnrollmentCurrent: 11,
    EnrollmentMax: 20,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10568,
    Code: "CSCI 481.001",
    Department: "CSCI",
    Title: "Capstone II",
    Instructors: [{ Username: "frashid", Name: "Rashid, Farzana" }],
    Hours: 2,
    Days: "MF",
    StartTime: "2019-05-07T13:30:00Z",
    EndTime: "2019-05-07T14:45:00Z",
    Location: { FullLocation: "RRO 217", Building: "RRO", Room: "217" },
    EnrollmentCurrent: 6,
    EnrollmentMax: 15,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10938,
    Code: "CSCI 481.002",
    Department: "CSCI",
    Title: "Capstone II",
    Instructors: [{ Username: "frashid", Name: "Rashid, Farzana" }],
    Hours: 2,
    Days: "WF",
    StartTime: "2019-05-07T13:30:00Z",
    EndTime: "2019-05-07T14:45:00Z",
    Location: { FullLocation: "RRO 217", Building: "RRO", Room: "217" },
    EnrollmentCurrent: 9,
    EnrollmentMax: 15,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10311,
    Code: "CSCI 499.001",
    Department: "CSCI",
    Title:
      "UGR in CSCI: Maximum Entropy Models *Permission of Instructor Required",
    Instructors: [{ Username: "kbogert", Name: "Bogert, Kenneth" }],
    Hours: 3,
    Days: null,
    StartTime: null,
    EndTime: null,
    Location: { FullLocation: null, Building: null, Room: null },
    EnrollmentCurrent: 1,
    EnrollmentMax: 10,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10312,
    Code: "CSCI 499.002",
    Department: "CSCI",
    Title:
      "UGR in CSCI: Computational Biology *Permission of Instructor Required",
    Instructors: [{ Username: "ksanft", Name: "Sanft, Kevin" }],
    Hours: 3,
    Days: null,
    StartTime: null,
    EndTime: null,
    Location: { FullLocation: null, Building: null, Room: null },
    EnrollmentCurrent: 0,
    EnrollmentMax: 10,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 10343,
    Code: "CSCI 499.003",
    Department: "CSCI",
    Title: "UGR in CSCI: Data Analytics *Permission of Instructor Required",
    Instructors: [{ Username: "ksanft", Name: "Sanft, Kevin" }],
    Hours: 3,
    Days: null,
    StartTime: null,
    EndTime: null,
    Location: { FullLocation: null, Building: null, Room: null },
    EnrollmentCurrent: 0,
    EnrollmentMax: 10,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11254,
    Code: "CSCI 499.004",
    Department: "CSCI",
    Title: "UGR in CSCI: Game Development *Permission of Instructor Required",
    Instructors: [{ Username: "awhitley", Name: "Whitley, Adam" }],
    Hours: 3,
    Days: null,
    StartTime: null,
    EndTime: null,
    Location: { FullLocation: "RRO 216", Building: "RRO", Room: "216" },
    EnrollmentCurrent: 0,
    EnrollmentMax: 5,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  },
  {
    CRN: 11255,
    Code: "CSCI 499.005",
    Department: "CSCI",
    Title: "UGR in CSCI: Game Design *Permission of Instructor Required",
    Instructors: [{ Username: "awhitley", Name: "Whitley, Adam" }],
    Hours: 1,
    Days: null,
    StartTime: null,
    EndTime: null,
    Location: { FullLocation: "RRO 216", Building: "RRO", Room: "216" },
    EnrollmentCurrent: 0,
    EnrollmentMax: 5,
    WaitlistMax: 0,
    WaitlistAvailable: 0,
    TermPart: "1",
    StartDate: "2023-01-09T05:00:00Z",
    EndDate: "2023-05-03T04:00:00Z",
    Classification: {
      DiversityIntensive: false,
      DiversityIntensiveR: false,
      DistanceLearning: false,
      FirstYearSeminar: false,
      Graduate: false,
      Honors: false,
      Arts: false,
      ServiceLearning: false,
      Open: true,
    },
    AdditionalMeetings: [],
    InstructionalMethod: "In-Person",
    Async: false,
  }
];
